Attribute VB_Name = "RS_TaskData"
Option Explicit
'==============================================================================
' ROLE STAFFING - RS_TaskData
'
' Task-level data that maintains itself: SameWorkAs, hammock tasks that borrow
' another task's dates, SpanCalc formulas, and the backfill and pre-flight that
' keep the rest honest.
'
' All four modules share one namespace, so nothing needs importing between them -
' but RoleStaffing holds the state they all use, so import that one first.
'==============================================================================

'==============================================================================
' COVERS: ROW IDS THAT FOLLOW THE ROWS
'
' You type row IDs into Covers, because they're the numbers on screen. Row IDs
' shift when tasks are inserted, deleted or moved, so a plain number written
' today quietly means a different task tomorrow.
'
' Project's own Predecessors column has the same problem and solves it by
' storing Unique IDs and merely DISPLAYING row IDs. Same trick here: the Unique
' IDs go in a hidden field, and Covers is rewritten from them whenever anything
' runs. Type row IDs, they keep pointing at the tasks you meant.
'
' Task Text7 holds  "<uids>;<the row IDs we last displayed>"
' so an edit can be told apart from a shift: if Covers still reads as we left
' it, the rows moved and we re-render; if it doesn't, you changed it and we
' re-read it.
'==============================================================================

' Is the event actually firing? Move a row, then run this. If "calculate events
' seen" hasn't moved, Project isn't raising the event for that operation on this
' build, and RS_SyncCovers is the fallback.
' Does this text name the task it's being typed into? Used by the guard to
' refuse a self-reference outright, the way Project refuses a self-predecessor.
' Accepts the row ID, "#33", and "u47", since all three are valid ways to write
' an entry.
Public Function IsSelfReference(t As Task, ByVal entry As String) As Boolean
    Dim x As Variant, ref As String

    entry = Trim$(entry)
    If entry = "" Then Exit Function
    If StrComp(entry, "none", vbTextCompare) = 0 Then Exit Function

    For Each x In Split(Replace(Replace(entry, ";", ","), " ", ","), ",")
        ref = Trim$(CStr(x))
        If ref <> "" Then
            If Left$(ref, 1) = "#" Then ref = Trim$(Mid$(ref, 2))
            If LCase$(Left$(ref, 1)) = "u" Then
                If IsNumeric(Mid$(ref, 2)) Then
                    If CLng(Mid$(ref, 2)) = t.UniqueID Then IsSelfReference = True: Exit Function
                End If
            ElseIf IsNumeric(ref) Then
                If RS_COVERS_BY_ROW_ID Then
                    If CLng(ref) = t.ID Then IsSelfReference = True: Exit Function
                Else
                    If CLng(ref) = t.UniqueID Then IsSelfReference = True: Exit Function
                End If
            End If
        End If
    Next x
End Function

' Everything the "block a self-reference as it's typed" event needs, so the event
' itself is one line. Signatures vary by Project version and I can't verify them
' from outside, so the Sub has to be generated by the editor's dropdowns - but
' its body doesn't have to be.
'
'   Cancel = RS_BlockSelfRef(tsk, Field, NewVal)
'
' Returns True when the edit should be refused, having already said why.
Public Function RS_BlockSelfRef(tsk As Task, ByVal fld As Long, ByVal NewVal As Variant) As Boolean
    On Error GoTo Quiet
    If Not gRS_GuardOn Or gRS_Suppress > 0 Then Exit Function
    If fld <> pjTaskText4 Then Exit Function
    If tsk Is Nothing Then Exit Function
    If Not IsSelfReference(tsk, CStr(NewVal)) Then Exit Function

    MsgBox "A task can't be the same work as itself." & vbCrLf & vbCrLf & _
           "Task " & tsk.ID & " - " & tsk.Name & vbCrLf & vbCrLf & _
           RS_COVERS_LABEL & " names the OTHER task: the one this is checking, or " & _
           "drafting, or whatever the rule pairs it with.", _
           vbExclamation, "Role Staffing"
    RS_BlockSelfRef = True
    Exit Function

Quiet:
    ' Never refuse an edit because this broke.
End Function

Public Sub RS_EventTest()
    Dim p As Project
    If Not HaveProject(p) Then Exit Sub
    EnsureCoverIndex p
    MsgBox "Guard running:            " & IIf(gRS_GuardOn, "YES", "NO - run RS_StartGuard") & vbCrLf & _
           "Calculate events seen:    " & gRS_CalcSeen & vbCrLf & _
           "Tasks referenced by " & RS_COVERS_LABEL & ": " & _
               IIf(mCoverUids Is Nothing, 0, mCoverUids.Count) & vbCrLf & _
           "Where they sit now:       " & Left$(CoverFingerprint(p), 120) & vbCrLf & _
           "Where they sat last sync: " & Left$(mCoverFp, 120) & vbCrLf & vbCrLf & _
           "Move a row and run this again. If the event count doesn't change, this " & _
           "Project build doesn't raise ProjectCalculate for that, and " & RS_COVERS_LABEL & _
           " has to be refreshed with RS_SyncCovers (menu 20).", vbInformation, "Role Staffing"
End Sub

Public Sub RS_SyncCovers()
    Dim p As Project
    If Not HaveProject(p) Then Exit Sub
    BuildCatalog p
    BuildRelationsRaw p
    MsgBox SyncCovers(p) & " Covers entr(ies) re-pointed after row changes.", _
           vbInformation, "Role Staffing"
End Sub

' Returns how many tasks had their displayed Covers rewritten.
Public Function SyncCovers(p As Project) As Long
    Dim t As Task, shown As String, stash As String, uids As String, lastShown As String
    Dim i As Long, changed As Long, nowShown As String, probs As New Collection
    Dim cleared As Long
    Dim parts As Variant, x As Variant, k As String, newUids As String

    If Not RS_COVERS_BY_ROW_ID Then Exit Function

    Set mCoverUids = NewDict()
    gRS_Suppress = gRS_Suppress + 1
    On Error Resume Next

    For Each t In p.Tasks
        If Not t Is Nothing Then
            shown = Trim$(TaskText(t, mF_SameWork))
            If shown <> "" And StrComp(shown, "none", vbTextCompare) <> 0 Then
                stash = Trim$(TaskText(t, mF_SwStash))
                uids = "": lastShown = ""
                i = InStr(stash, ";")
                If i > 0 Then
                    uids = Left$(stash, i - 1)
                    lastShown = Mid$(stash, i + 1)
                End If

                If uids <> "" And StrComp(shown, lastShown, vbTextCompare) = 0 Then
                    ' untouched since we wrote it, so any difference is the rows moving
                    NoteCoverUids uids
                    nowShown = RowIdsFor(uids)
                    If nowShown <> "" And StrComp(nowShown, shown, vbTextCompare) <> 0 Then
                        SetTaskText t, mF_SameWork, nowShown
                        SetTaskText t, mF_SwStash, uids & ";" & nowShown
                        changed = changed + 1
                    End If
                Else
                    ' typed or pasted by hand - read it and remember what it points at
                    newUids = ""
                    parts = Split(Replace(Replace(shown, ";", ","), " ", ","), ",")
                    For Each x In parts
                        If Trim$(CStr(x)) <> "" Then
                            k = ResolveCoverRef(CStr(x), probs)
                            If k = CStr(t.UniqueID) Then k = ""     ' never itself
                            If k <> "" Then
                                If newUids <> "" Then newUids = newUids & ","
                                newUids = newUids & k
                            End If
                        End If
                    Next x
                    If newUids <> "" Then
                        NoteCoverUids newUids
                        nowShown = RowIdsFor(newUids)
                        If nowShown <> "" Then SetTaskText t, mF_SameWork, nowShown
                        SetTaskText t, mF_SwStash, newUids & ";" & nowShown
                    Else
                        ' Everything in it was rubbish - most often the task's own
                        ' number. Clearing it is the point: leaving the text there
                        ' means it survives every run and looks accepted.
                        SetTaskText t, mF_SameWork, ""
                        SetTaskText t, mF_SwStash, ""
                        cleared = cleared + 1
                    End If
                End If
            ElseIf Trim$(TaskText(t, mF_SwStash)) <> "" Then
                SetTaskText t, mF_SwStash, ""                      ' Covers cleared - drop the memory
            End If
        End If
    Next t

    On Error GoTo 0
    gRS_Suppress = gRS_Suppress - 1
    mCoverFp = CoverFingerprint(p)
    gRS_CoversCleared = cleared
    SyncCovers = changed
End Function

' A cheap summary of where the referenced tasks currently sit. ProjectCalculate
' fires constantly, so comparing this is how we avoid a full scan every time.
Public Function CoverFingerprint(p As Project) As String
    Dim k As Variant, s As String, t As Task
    If mCoverUids Is Nothing Then Exit Function
    For Each k In mCoverUids.Keys
        Set t = TaskByUid(p, CLng(k))
        If Not t Is Nothing Then s = s & k & ":" & t.ID & "|"
    Next k
    CoverFingerprint = s
End Function

' Makes sure we know what every SameWorkAs points at. Until this has run the
' index is empty, so nothing can be detected as stale - which meant a row moved
' in a fresh session did nothing until some macro happened to run.
'
' Cheap when there is nothing to do: one pass reading one field per task, and
' only a full resolve when the file actually uses SameWorkAs.
Public Sub EnsureCoverIndex(p As Project)
    Dim t As Task, anySet As Boolean

    On Error GoTo Quiet
    If StrComp(mCoverScanned, p.Name, vbTextCompare) = 0 Then
        If Not mCoverUids Is Nothing Then Exit Sub
    End If

    For Each t In p.Tasks
        If Not t Is Nothing Then
            If Trim$(TaskText(t, mF_SameWork)) <> "" Then
                anySet = True
                Exit For
            End If
        End If
    Next t

    If Not anySet Then
        Set mCoverUids = NewDict()
        mCoverFp = ""
        mCoverScanned = p.Name
        Exit Sub
    End If

    BuildCatalog p
    BuildRelationsRaw p
    SyncCovers p
    mCoverScanned = p.Name          ' only once it actually worked
Quiet:
End Sub

' Called from the ProjectCalculate event. Resyncs only if something actually
' moved - there is no hook that fires when a column is drawn, so this is as
' close to "updates itself" as Project allows.
Public Sub CoversMaybeStale(p As Project)
    Dim fp As String
    On Error GoTo Quiet
    If gRS_Suppress > 0 Then Exit Sub

    gRS_CalcSeen = gRS_CalcSeen + 1
    EnsureCoverIndex p
    If mCoverUids Is Nothing Then Exit Sub
    If mCoverUids.Count = 0 Then Exit Sub

    fp = CoverFingerprint(p)
    If fp = mCoverFp Then Exit Sub

    BuildCatalog p
    BuildRelationsRaw p
    SyncCovers p
Quiet:
End Sub

' "47,52" -> "33,38" using where those tasks sit right now.
Private Sub NoteCoverUids(ByVal uids As String)
    Dim x As Variant
    If mCoverUids Is Nothing Then Set mCoverUids = NewDict()
    For Each x In Split(uids, ",")
        If Trim$(CStr(x)) <> "" Then mCoverUids(Trim$(CStr(x))) = True
    Next x
End Sub

Private Function RowIdsFor(ByVal uids As String) As String
    Dim x As Variant, s As String, k As String
    For Each x In Split(uids, ",")
        k = Trim$(CStr(x))
        If mTasks.Exists(k) Then
            If s <> "" Then s = s & ","
            s = s & TaskIdOf(k)
        End If
    Next x
    RowIdsFor = s
End Function


'==============================================================================
' HAMMOCK TASKS
'
' A task whose dates are borrowed from another task, so it lasts exactly as long
' as that one does. Redline support is the case this exists for: 64 hours of
' keeping manufacturing prints moving, spread across the whole of a deliverable,
' as a real task row rather than an assignment hidden on a summary.
'
' Task Text8 holds the Unique ID of the task it spans. Dates are re-borrowed
' whenever anything runs, so it follows when the spanned work moves or stretches.
'
' The task is set to manually scheduled, which is what lets its dates be borrowed
' rather than computed from links. That also means levelling leaves it alone -
' correct here: a trickle spread across months shouldn't be pushed anywhere, and
' its hours still count against whoever is doing it.
'==============================================================================

Public Sub RS_SpanTask()
    Dim p As Project
    If Not HaveProject(p) Then Exit Sub

    Dim sel As Tasks, t As Task, target As Task, answer As String, k As String
    Dim n As Long, probs As New Collection

    On Error Resume Next
    Set sel = ActiveSelection.Tasks
    On Error GoTo 0
    If sel Is Nothing Then
        MsgBox "Select the task that should span another one - the Redline row, say - " & _
               "then run this.", vbInformation, "Role Staffing"
        Exit Sub
    End If
    If sel.Count = 0 Then
        MsgBox "Select the task that should span another one first.", vbInformation, "Role Staffing"
        Exit Sub
    End If

    BuildCatalog p
    BuildRelationsRaw p

    answer = InputBox( _
        "Which task should the selected task(s) span?" & vbCrLf & vbCrLf & _
        "Type its row ID - usually a summary, e.g. the deliverable this support " & _
        "runs alongside." & vbCrLf & vbCrLf & _
        "(You can also just type the row number straight into the " & RS_SPANS_LABEL & _
        " column - this does the same thing.)" & vbCrLf & vbCrLf & _
        "The selected task will start when that one starts, finish when it " & _
        "finishes, and follow it from then on. Its Work stays as you set it, so " & _
        "the hours spread across the span." & vbCrLf & vbCrLf & _
        "Leave blank and press OK to stop spanning.", _
        "Span another task")
    If StrPtr(answer) = 0 Then Exit Sub

    Application.OpenUndoTransaction "Role Staffing: span"
    gRS_Suppress = gRS_Suppress + 1
    On Error Resume Next

    If Trim$(answer) = "" Then
        For Each t In sel
            If Not t Is Nothing Then
                SetTaskText t, mF_Spans, ""
                n = n + 1
            End If
        Next t
        gRS_Suppress = gRS_Suppress - 1
        Application.CloseUndoTransaction
        MsgBox n & " task(s) no longer span anything. Their dates are their own again.", _
               vbInformation, "Role Staffing"
        Exit Sub
    End If

    k = ResolveCoverRef(answer, probs)
    If k = "" Then
        gRS_Suppress = gRS_Suppress - 1
        Application.CloseUndoTransaction
        MsgBox "No task matches """ & answer & """.", vbExclamation, "Role Staffing"
        Exit Sub
    End If

    For Each t In sel
        If Not t Is Nothing Then
            If CStr(t.UniqueID) = k Then
                probs.Add "Task " & t.ID & " can't span itself."
            Else
                SetTaskText t, mF_Spans, CStr(TaskIdOf(k))        ' the row number, same as typing it
                SetTaskText t, mF_SpanStash, ""                       ' let RefitSpans resolve and stash it
                n = n + 1
            End If
        End If
    Next t

    gRS_Suppress = gRS_Suppress - 1
    Application.CloseUndoTransaction

    RefitSpans p

    Set target = TaskByUid(p, CLng(k))
    MsgBox n & " task(s) now span task " & TaskIdOf(k) & " - " & TaskNameOf(k) & "." & vbCrLf & vbCrLf & _
           IIf(target Is Nothing, "", "That runs " & Format$(target.Start, "yyyy-mm-dd") & " to " & _
               Format$(target.Finish, "yyyy-mm-dd") & "." & vbCrLf & vbCrLf) & _
           "They'll follow it from now on. Set Work to the total hours you want spread " & _
           "across that span, then RS_Suggest will staff it from the role pool.", _
           vbInformation, "Role Staffing"
End Sub

' Keeps Spans honest and re-borrows the dates.
'
' Works exactly like SameWorkAs: you type a ROW ID, it's stored as a Unique ID
' in Task Text9, and the cell is re-rendered as a row ID whenever anything runs.
' So it shows the number you typed, and still points at the right task after
' rows move.
' Passes, not one sweep: a hammock spanning another hammock has to wait for
' that one to borrow its own dates first, and tasks are walked in file order.
' Same reason SameWorkAs needs transitive closure. Stops as soon as a pass
' changes nothing.
Public Function RefitSpans(p As Project) As Long
    Dim pass As Long, moved As Long
    For pass = 1 To 5
        moved = RefitSpansOnce(p)
        RefitSpans = RefitSpans + moved
        If moved = 0 Then Exit For
    Next pass
End Function

Private Function RefitSpansOnce(p As Project) As Long
    Dim t As Task, target As Task, n As Long
    Dim shown As String, stash As String, uid As String, lastShown As String
    Dim i As Long, nowShown As String, probs As New Collection
    Dim keepWork As Double

    gRS_Suppress = gRS_Suppress + 1
    On Error Resume Next

    For Each t In p.Tasks
        If Not t Is Nothing Then
            shown = Trim$(TaskText(t, mF_Spans))
            If shown = "" Then
                If Trim$(TaskText(t, mF_SpanStash)) <> "" Then SetTaskText t, mF_SpanStash, ""
            Else
                stash = Trim$(TaskText(t, mF_SpanStash))
                uid = "": lastShown = ""
                i = InStr(stash, ";")
                If i > 0 Then
                    uid = Left$(stash, i - 1)
                    lastShown = Mid$(stash, i + 1)
                End If

                If uid = "" Or StrComp(shown, lastShown, vbTextCompare) <> 0 Then
                    ' typed by hand - work out what it points at
                    uid = ResolveCoverRef(shown, probs)
                    If uid = CStr(t.UniqueID) Then uid = ""      ' can't span itself
                End If

                If uid = "" Then
                    SetTaskText t, mF_Spans, ""
                    SetTaskText t, mF_SpanStash, ""
                Else
                    nowShown = RowIdsFor(uid)
                    If nowShown <> "" Then
                        If StrComp(nowShown, shown, vbTextCompare) <> 0 Then SetTaskText t, mF_Spans, nowShown
                        SetTaskText t, mF_SpanStash, uid & ";" & nowShown
                    End If

                    Set target = Nothing
                    Set target = TaskByUid(p, CLng(uid))
                    If target Is Nothing Then
                        SetTaskText t, mF_Spans, ""
                        SetTaskText t, mF_SpanStash, ""
                    Else
                        ' manual scheduling is what lets dates be set outright
                        t.Manual = True

                        ' FIXED WORK BEFORE THE DATES, and this order is the
                        ' whole fix. On a Fixed Units task Project recalculates
                        '
                        '     Work = Units x Duration
                        '
                        ' when the duration changes. Stretching a 64-hour
                        ' hammock across nine months therefore multiplied its
                        ' hours by the stretch instead of thinning them - the
                        ' exact opposite of what a hammock is for. Fixed Work
                        ' makes Project hold the hours and drop the units, which
                        ' is "spread the same 64 hours over the whole span".
                        '
                        ' RS_PrepFile sets this type on everything, but only on
                        ' the tasks that existed when it last ran - a hammock
                        ' set up afterwards never got it.
                        If ToDbl(t.Duration) > 0 Then
                            If ToDbl(t.Type) <> PJ_FIXED_WORK Then t.Type = PJ_FIXED_WORK
                        End If

                        If t.Start <> target.Start Or t.Finish <> target.Finish Then
                            keepWork = ToDbl(t.Work)
                            t.Start = target.Start
                            t.Finish = target.Finish
                            n = n + 1

                            ' Belt and braces: Project refuses the type change in
                            ' some states, and silently. Put the hours back
                            ' rather than leave them inflated - a wrong total is
                            ' worse than a wrong unit rate, because the total is
                            ' what the plan is costed on.
                            If keepWork > 0 Then
                                If Abs(ToDbl(t.Work) - keepWork) > 0.5 Then t.Work = keepWork
                            End If
                        End If
                    End If
                End If
            End If
        End If
    Next t

    On Error GoTo 0
    gRS_Suppress = gRS_Suppress - 1
    RefitSpansOnce = n
End Function

'==============================================================================
' SPANCALC: WORK AS A FORMULA
'
' Put an expression in the SpanCalc column and this task's Work becomes whatever
' it evaluates to, in hours, recalculated whenever anything runs.
'
'     =(#20 * 0.20) + (#11 * 0.05)
'
' #20 is the Work of the task on row 20, in hours - for a summary that's the
' rollup, so #20 on an 787 h deliverable is 787. Row IDs follow the rows, same
' as everywhere else; u47 pins one to a Unique ID.
'
' Supports + - * / ( ) and negatives. The leading = is optional.
'
' Redline at a fifth of the drafting it supports is the case this exists for:
' the budget moves when the work it's proportional to moves, instead of being a
' number somebody remembers to revisit.
'
' Chains work - a formula referring to a task that itself has a formula - by
' evaluating a few times until the numbers settle.
'==============================================================================

Public Function RefitCalcs(p As Project) As Long
    Dim t As Task, expr As String, hrs As Double, n As Long, pass As Long
    Dim changed As Boolean, before As Double

    Set mCalcProj = p
    gRS_Suppress = gRS_Suppress + 1
    On Error Resume Next

    ' A few passes, so a formula referring to a calculated task settles.
    For pass = 1 To 3
        changed = False
        For Each t In p.Tasks
            If Not t Is Nothing Then
                expr = Trim$(TaskText(t, mF_Calc))
                If expr <> "" Then
                    hrs = EvalCalc(t, expr)
                    If mCalcBad = "" And hrs >= 0 Then
                        before = ToDbl(t.Work) / 60#
                        If Abs(before - hrs) > 0.01 Then
                            t.Work = hrs * 60#
                            changed = True
                            If pass = 1 Then n = n + 1
                        End If
                    End If
                End If
            End If
        Next t
        If Not changed Then Exit For
    Next pass

    On Error GoTo 0
    gRS_Suppress = gRS_Suppress - 1
    RefitCalcs = n
End Function

' Hours, or -1 with mCalcBad set.
Public Function EvalCalc(t As Task, ByVal expr As String) As Double
    Dim v As Double
    mCalcBad = ""
    expr = Trim$(expr)
    If Left$(expr, 1) = "=" Then expr = Mid$(expr, 2)

    mCalcSrc = Replace(expr, " ", "")
    mCalcPos = 1
    If mCalcSrc = "" Then
        mCalcBad = "empty"
        EvalCalc = -1
        Exit Function
    End If

    v = CalcExpr(t)
    If mCalcBad = "" And mCalcPos <= Len(mCalcSrc) Then
        mCalcBad = "didn't understand """ & Mid$(mCalcSrc, mCalcPos) & """"
    End If
    If mCalcBad <> "" Then
        EvalCalc = -1
    Else
        EvalCalc = v
    End If
End Function

Public Function CalcError() As String
    CalcError = mCalcBad
End Function

' expr = term (('+'|'-') term)*
Private Function CalcExpr(t As Task) As Double
    Dim v As Double, op As String
    v = CalcTerm(t)
    Do While mCalcBad = "" And mCalcPos <= Len(mCalcSrc)
        op = Mid$(mCalcSrc, mCalcPos, 1)
        If op <> "+" And op <> "-" Then Exit Do
        mCalcPos = mCalcPos + 1
        If op = "+" Then v = v + CalcTerm(t) Else v = v - CalcTerm(t)
    Loop
    CalcExpr = v
End Function

' term = factor (('*'|'/') factor)*
Private Function CalcTerm(t As Task) As Double
    Dim v As Double, op As String, d As Double
    v = CalcFactor(t)
    Do While mCalcBad = "" And mCalcPos <= Len(mCalcSrc)
        op = Mid$(mCalcSrc, mCalcPos, 1)
        If op <> "*" And op <> "/" Then Exit Do
        mCalcPos = mCalcPos + 1
        d = CalcFactor(t)
        If op = "*" Then
            v = v * d
        ElseIf Abs(d) < 0.000001 Then
            mCalcBad = "divide by zero"
        Else
            v = v / d
        End If
    Loop
    CalcTerm = v
End Function

' factor = number | #ref | (expr) | -factor
Private Function CalcFactor(t As Task) As Double
    Dim ch As String, num As String, ref As String, other As Task, probs As New Collection
    Dim k As String

    If mCalcPos > Len(mCalcSrc) Then
        mCalcBad = "expression stops early"
        Exit Function
    End If
    ch = Mid$(mCalcSrc, mCalcPos, 1)

    If ch = "-" Then
        mCalcPos = mCalcPos + 1
        CalcFactor = -CalcFactor(t)
        Exit Function
    End If

    If ch = "(" Then
        mCalcPos = mCalcPos + 1
        CalcFactor = CalcExpr(t)
        If mCalcBad <> "" Then Exit Function
        If mCalcPos > Len(mCalcSrc) Then
            mCalcBad = "missing )"
        ElseIf Mid$(mCalcSrc, mCalcPos, 1) <> ")" Then
            mCalcBad = "missing )"
        Else
            mCalcPos = mCalcPos + 1
        End If
        Exit Function
    End If

    If ch = "#" Or LCase$(ch) = "u" Then
        ref = ch
        mCalcPos = mCalcPos + 1
        Do While mCalcPos <= Len(mCalcSrc)
            ch = Mid$(mCalcSrc, mCalcPos, 1)
            If ch < "0" Or ch > "9" Then Exit Do
            ref = ref & ch
            mCalcPos = mCalcPos + 1
        Loop
        If Len(ref) < 2 Then
            mCalcBad = "a # needs a task number after it"
            Exit Function
        End If

        k = ResolveCoverRef(ref, probs)
        If k = "" Then
            mCalcBad = "no task matches " & ref
            Exit Function
        End If
        If k = CStr(t.UniqueID) Then
            mCalcBad = "a task can't be a function of itself"
            Exit Function
        End If
        Set other = TaskByUid(mCalcProj, CLng(k))
        If other Is Nothing Then
            mCalcBad = "no task matches " & ref
            Exit Function
        End If
        CalcFactor = ToDbl(other.Work) / 60#
        Exit Function
    End If

    Do While mCalcPos <= Len(mCalcSrc)
        ch = Mid$(mCalcSrc, mCalcPos, 1)
        If (ch >= "0" And ch <= "9") Or ch = "." Then
            num = num & ch
            mCalcPos = mCalcPos + 1
        Else
            Exit Do
        End If
    Loop
    If num = "" Or Not IsNumeric(num) Then
        mCalcBad = "didn't understand """ & Mid$(mCalcSrc, mCalcPos) & """"
        Exit Function
    End If
    CalcFactor = CDbl(num)
End Function


'==============================================================================
' BACKFILL
'
' Works out the Role for assignments that already exist, from what's sitting in
' Resource Names, and writes it down. Without this, the role a person is filling
' is only recorded when RS_Apply swaps a bucket out - so a schedule you staffed
' by hand, or pasted in, has nothing for the rules to work from.
'
' Assignment rows:  the resource is a bucket      -> its IsRole
'                   the person has exactly 1 role -> that role
' Task rows:        every assignment agrees on one role -> that role
'
' Never overwrites anything already filled in. Runs at the end of RS_Setup, and
' safe to re-run any time.
'==============================================================================

Public Sub RS_BackfillRoles()
    Dim p As Project
    If Not HaveProject(p) Then Exit Sub
    BackfillRoles p, True
End Sub

' MIGRATING AN EXISTING SCHEDULE
'
' If your Gantt already has role names in Resource Names - Engineer, Checker,
' Draft - those rows are roles, not people, but nothing in the file says so.
' This marks them (sets IsRole), then records the role on every assignment that
' uses them, so RS_Suggest can start swapping in real people.
'
' Run this ONCE on an existing file, before RS_Suggest.
Public Sub RS_MarkRoles()
    Dim p As Project
    If Not HaveProject(p) Then Exit Sub

    FastOn "marking role rows"
    Dim r As Resource, all As String, answer As String
    Dim parts As Variant, x As Variant, s As String, nm As String, role As String
    Dim i As Long, marked As Long, rep As New Collection, miss As New Collection

    ' Offer every resource name, so it's a matter of deleting the real people
    For Each r In p.Resources
        If Not r Is Nothing Then
            If all <> "" Then all = all & ", "
            all = all & r.Name
        End If
    Next r
    If all = "" Then
        MsgBox "This project has no resources.", vbInformation, "Role Staffing"
        Exit Sub
    End If

    answer = InputBox( _
        "Which of these resources are ROLES rather than real people?" & vbCrLf & vbCrLf & _
        "Delete the actual people and leave the roles." & vbCrLf & vbCrLf & _
        "If a row's name isn't the role name, say so with = :" & vbCrLf & _
        "    Checker=Check, Redline Support=Redline" & vbCrLf & vbCrLf & _
        "Everything left here becomes an unstaffed slot that RS_Suggest fills.", _
        "Role Staffing - mark the role rows", all)
    If Trim$(answer) = "" Then Exit Sub

    Application.OpenUndoTransaction "Role Staffing: mark role resources"
    gRS_Suppress = gRS_Suppress + 1
    On Error GoTo Fail

    parts = Split(answer, ",")
    For Each x In parts
        s = Trim$(CStr(x))
        If s <> "" Then
            i = InStr(s, "=")
            If i > 0 Then
                nm = Trim$(Left$(s, i - 1))
                role = Trim$(Mid$(s, i + 1))
            Else
                nm = s
                role = s
                ' tolerate the old "Role: Draft" convention
                If StrComp(Left$(nm, 6), "Role: ", vbTextCompare) = 0 Then role = Trim$(Mid$(nm, 7))
            End If

            Set r = ResourceByName(p, nm)
            If r Is Nothing Then
                miss.Add """" & nm & """ - no resource with that name."
            ElseIf role = "" Then
                miss.Add """" & nm & """ - couldn't work out a role name. Use Name=Role."
            Else
                r.Text2 = role                      ' IsRole
                r.Text1 = ""                        ' a role row has no RoleAvail
                If ToFraction(r.MaxUnits) < 5 Then r.MaxUnits = RS_BUCKET_UNITS
                marked = marked + 1
                rep.Add r.Name & "   ->   role """ & role & """"
            End If
        End If
    Next x

    gRS_Suppress = gRS_Suppress - 1
    Application.CloseUndoTransaction

    If marked = 0 Then
        Dim m As String, y As Variant
        For Each y In miss
            m = m & CStr(y) & vbCrLf
        Next y
        MsgBox "Nothing was marked." & vbCrLf & vbCrLf & m, vbExclamation, "Role Staffing"
        Exit Sub
    End If

    ' Now record the role on every assignment using those rows
    BackfillRoles p, False

    Dim out As New Collection
    out.Add marked & " resource row(s) are now roles. Their Max Units was raised so unstaffed"
    out.Add "demand doesn't read as an overallocated person."
    out.Add ""
    AddSection out, "MARKED AS ROLES (" & rep.Count & ")", rep
    If miss.Count > 0 Then AddSection out, "NOT DONE (" & miss.Count & ")", miss
    out.Add "NEXT STEPS"
    out.Add "----------"
    out.Add "   1. Run RS_Setup, so the fields are named and the views exist."
    out.Add "   2. On the resource sheet, give each real person a Max Units and a RoleAvail,"
    out.Add "      e.g. " & Chr$(34) & "Check:40*,Draft:20" & Chr$(34) & ". Until you do, nobody is a candidate for anything."
    out.Add "   3. RS_Suggest, review the Suggested column, then RS_Apply."
    out.Add "   4. RS_Level to see what it does to the finish date."
    ShowReport "Mark Role Resources", out

    MsgBox marked & " resource row(s) marked as roles, and the role recorded on their" & vbCrLf & _
           "assignments." & vbCrLf & vbCrLf & _
           "Next: fill in Max Units and RoleAvail for your real people, then run RS_Suggest. " & _
           "Nobody can be suggested for a role that isn't in their RoleAvail.", _
           vbInformation, "Role Staffing"
    Exit Sub

Fail:
    FastOff
    gRS_Suppress = gRS_Suppress - 1
    Application.CloseUndoTransaction
    MsgBox "Marking roles failed: " & Err.Description, vbExclamation, "Role Staffing"
End Sub

Public Sub BackfillRoles(p As Project, ByVal talk As Boolean)
    Dim t As Task, a As Assignment, r As Resource, role As String
    Dim asgDone As Long, taskDone As Long
    Dim rep As New Collection, stuck As New Collection, mixed As New Collection
    Dim roles As Object, k As Variant, only As String

    FastOn "recording roles"
    BuildCatalog p

    Application.OpenUndoTransaction "Role Staffing: backfill roles"
    gRS_Suppress = gRS_Suppress + 1
    On Error GoTo Fail

    For Each t In p.Tasks
        If Not t Is Nothing Then
            Set roles = NewDict()

            For Each a In t.Assignments
                Set r = ResourceOf(p, a)
                If Not r Is Nothing Then
                    role = ""
                    If IsBucket(r) Then
                        role = BucketRole(r)
                    ElseIf r.Type = pjResourceTypeWork Then
                        If GetAsgRole(a) <> "" Then
                            role = NormalizeRole(GetAsgRole(a))
                        ElseIf RoleCount(r) = 1 Then
                            role = OnlyRole(r)
                        End If
                    End If

                    If role <> "" Then
                        roles(UCase$(role)) = role
                        If GetAsgRole(a) = "" Then
                            SetAsgRole a, role
                            asgDone = asgDone + 1
                            rep.Add "Task " & t.ID & " " & t.Name & ": " & r.Name & " -> " & role
                        End If
                    ElseIf IsWorkPerson(r) Then
                        If RoleCount(r) = 0 Then
                            stuck.Add "Task " & t.ID & " " & t.Name & ": " & r.Name & _
                                      " has no RoleAvail, so there's no role to record."
                        Else
                            stuck.Add "Task " & t.ID & " " & t.Name & ": " & r.Name & _
                                      " does several roles - set Role on their assignment row."
                        End If
                    End If
                End If
            Next a

            ' Task-level Role, only when there's no ambiguity
            If GetTaskRoleRaw(t) = "" And roles.Count > 0 Then
                If roles.Count = 1 Then
                    For Each k In roles.Keys
                        only = CStr(roles(k))
                    Next k
                    SetTaskText t, mF_Role, only
                    taskDone = taskDone + 1
                Else
                    mixed.Add "Task " & t.ID & " " & t.Name & ": carries " & RolesList(roles) & _
                              " - left Role blank on the task row (the assignment rows have it)."
                End If
            End If
        End If
    Next t

    gRS_Suppress = gRS_Suppress - 1
    Application.CloseUndoTransaction

    If Not talk Then Exit Sub

    Dim out As New Collection
    out.Add "Filled in Role on " & asgDone & " assignment row(s) and " & taskDone & " task row(s)."
    out.Add "Nothing already filled in was changed."
    out.Add ""
    AddSection out, "FILLED IN (" & rep.Count & ")", rep
    AddSection out, "COULDN'T WORK IT OUT (" & stuck.Count & ")", stuck
    AddSection out, "MORE THAN ONE ROLE ON THE TASK (" & mixed.Count & ")", mixed
    ShowReport "Backfill Roles", out

    MsgBox asgDone & " assignment row(s) and " & taskDone & " task row(s) now have a Role." & _
           IIf(stuck.Count > 0, vbCrLf & vbCrLf & stuck.Count & " couldn't be worked out - see the report.", ""), _
           vbInformation, "Role Staffing"
    Exit Sub

Fail:
    FastOff
    gRS_Suppress = gRS_Suppress - 1
    Application.CloseUndoTransaction
    If talk Then MsgBox "Backfill failed: " & Err.Description, vbExclamation, "Role Staffing"
End Sub

Private Function RolesList(roles As Object) As String
    Dim k As Variant, s As String
    For Each k In roles.Keys
        If s <> "" Then s = s & " + "
        s = s & CStr(roles(k))
    Next k
    RolesList = s
End Function


'==============================================================================
' PREP AND PRE-FLIGHT
'
' Checks the file is in a state where the rest of this can work, then offers to
' fix what's fixable. Run it before staffing, and any time the schedule has been
' worked on by hand.
'
' Fixes:  manually scheduled -> auto scheduled
'         task type -> Fixed Work, so reducing somebody's rate lengthens the
'         task instead of quietly reducing the work
'         new tasks default to auto scheduled
'         levelling allowed to move past existing slack
'
' Reports but cannot fix: tasks with no Work, role rows with no people, missing
' links. Those need a decision, not a default.
'==============================================================================

Public Sub RS_PrepFile()
    Dim p As Project
    If Not HaveProject(p) Then Exit Sub
    FastOn "checking the file"

    Dim t As Task, a As Assignment, r As Resource
    Dim manual As Long, wrongType As Long, noWork As Long, loe As Long
    Dim staffable As Long, unlinked As Long, tot As Long
    Dim rep As New Collection, fixable As Long

    BuildCatalog p

    ' ---- look ------------------------------------------------------------
    For Each t In p.Tasks
        If Not t Is Nothing Then
            If Not CBool(t.Summary) Then
                tot = tot + 1
                If IsManual(t) And Trim$(TaskText(t, mF_Spans)) = "" Then manual = manual + 1
                If ToDbl(t.Type) <> PJ_FIXED_WORK And ToDbl(t.Duration) > 0 Then
                    wrongType = wrongType + 1
                End If

                Dim hasRole As Boolean
                hasRole = False
                For Each a In t.Assignments
                    If IsBucket(ResourceOf(p, a)) Then hasRole = True
                Next a
                If hasRole Then
                    staffable = staffable + 1
                    If ToDbl(t.Work) <= 0 Then noWork = noWork + 1
                    If PredsCount(t) = 0 Then unlinked = unlinked + 1
                End If
            ElseIf t.Assignments.Count > 0 Then
                loe = loe + 1
            End If
        End If
    Next t

    fixable = manual + wrongType

    rep.Add "WHAT'S THERE"
    rep.Add "------------"
    rep.Add "   " & PadL(CStr(tot), 6) & "  tasks (not counting summaries)"
    rep.Add "   " & PadL(CStr(staffable), 6) & "  have a role row on them, so they're slots to staff"
    rep.Add ""
    rep.Add "FIXABLE FROM HERE"
    rep.Add "-----------------"
    rep.Add "   " & PadL(CStr(manual), 6) & "  manually scheduled - levelling ignores these entirely"
    rep.Add "   " & PadL(CStr(wrongType), 6) & "  not Fixed Work - reducing somebody's rate would change the"
    rep.Add "           WORK instead of the dates, so nothing stretches and the"
    rep.Add "           finish date comes out optimistic"
    rep.Add ""
    rep.Add "NEEDS YOU"
    rep.Add "---------"
    If noWork > 0 Then
        rep.Add "   " & PadL(CStr(noWork), 6) & "  slots have NO WORK in hours. Work is what the whole"
        rep.Add "           calculation runs on - these get skipped. Enter hours."
    Else
        rep.Add "        0  slots missing Work"
    End If
    If unlinked > 0 Then
        rep.Add "   " & PadL(CStr(unlinked), 6) & "  slots have no predecessor. Fine if they genuinely start"
        rep.Add "           cold, but " & IIf(RulesText() = "", "rules", RulesText()) & " needs links to"
        rep.Add "           find the work a check covers."
    End If
    If loe > 0 Then
        rep.Add "   " & PadL(CStr(loe), 6) & "  summary tasks carry assignments (level-of-effort). Project"
        rep.Add "           will not level those, and RS_Schedule doesn't count them."
    End If
    rep.Add ""
    rep.Add "SETTINGS"
    rep.Add "--------"
    rep.Add "   Hours per week: " & Format$(ToDbl(p.HoursPerWeek), "0.#") & _
            "   (File > Options > Schedule - this drives every capacity number)"
    rep.Add "   Roles found:    " & IIf(RoleNames().Count = 0, "NONE - fill in RoleAvail", _
                                        JoinCollection(RoleNames(), ", "))
    rep.Add ""

    ' ---- offer to fix ------------------------------------------------------
    If fixable = 0 Then
        FastOff
        ShowReport "File Check", rep
        MsgBox "Tasks look right: nothing manually scheduled, everything Fixed Work." & vbCrLf & vbCrLf & _
               IIf(noWork > 0, noWork & " slot(s) have no Work in hours and will be skipped - " & _
                   "see the report." & vbCrLf & vbCrLf, "") & _
               "Next: RS_Validate, then RS_AutoStaff.", vbInformation, "Role Staffing"
        Exit Sub
    End If

    If MsgBox("Fix " & fixable & " task(s)?" & vbCrLf & vbCrLf & _
              manual & " manually scheduled  ->  auto scheduled" & vbCrLf & _
              wrongType & " not Fixed Work     ->  Fixed Work" & vbCrLf & vbCrLf & _
              "Also sets new tasks to auto scheduled, and lets levelling move past " & _
              "existing slack." & vbCrLf & vbCrLf & _
              "One Undo puts it all back. Dates may move as Project recalculates.", _
              vbOKCancel + vbQuestion, "Role Staffing") <> vbOK Then
        FastOff
        ShowReport "File Check", rep
        Exit Sub
    End If

    ' Only now, with permission. EnsureCoverIndex brings the self-maintaining
    ' columns up to date, which WRITES - doing it during the survey meant
    ' cancelling the dialog still left the file changed.
    EnsureCoverIndex p

    Dim didManual As Long, didType As Long, failType As Long
    Application.OpenUndoTransaction "Role Staffing: prepare file"
    gRS_Suppress = gRS_Suppress + 1
    On Error Resume Next

    For Each t In p.Tasks
        If Not t Is Nothing Then
            If Not CBool(t.Summary) Then
                ' A hammock is manually scheduled on purpose - that's what lets
                ' its dates be borrowed. Forcing it back to auto would undo it.
                If IsManual(t) And Trim$(TaskText(t, mF_Spans)) = "" Then
                    t.Manual = False
                    If Not IsManual(t) Then didManual = didManual + 1
                End If
                If ToDbl(t.Type) <> PJ_FIXED_WORK And ToDbl(t.Duration) > 0 Then
                    t.Type = PJ_FIXED_WORK
                    If ToDbl(t.Type) = PJ_FIXED_WORK Then
                        didType = didType + 1
                    Else
                        failType = failType + 1
                    End If
                End If
            End If
        End If
    Next t

    p.NewTasksAreManual = False
    Err.Clear
    PA.LevelingOptions Automatic:=False, LevelWithinSlack:=False, _
                       LevelIndividual:=True, LevelCanSplit:=True
    If Err.Number <> 0 Then
        Err.Clear
        PA.LevelingOptions False, , False, True, True
    End If
    Dim levelSet As Boolean
    levelSet = (Err.Number = 0)
    Err.Clear

    gRS_Suppress = gRS_Suppress - 1
    Application.CloseUndoTransaction
    On Error GoTo 0
    FastOff

    rep.Add "WHAT I CHANGED"
    rep.Add "--------------"
    rep.Add "   " & didManual & " task(s) switched to auto scheduled"
    rep.Add "   " & didType & " task(s) switched to Fixed Work"
    If failType > 0 Then
        rep.Add "   " & failType & " task(s) REFUSED the type change - usually a constraint or"
        rep.Add "     actuals already entered. Change those by hand, or accept that they"
        rep.Add "     won't stretch."
    End If
    If Not levelSet Then
        rep.Add ""
        rep.Add "   Couldn't set the levelling options. Do it by hand, once:"
        rep.Add "     Resource > Level > Levelling Options..."
        rep.Add "     UNTICK ""Level only within available slack"""
    End If
    ShowReport "File Check", rep

    MsgBox didManual & " task(s) now auto scheduled, " & didType & " now Fixed Work." & vbCrLf & vbCrLf & _
           IIf(failType > 0, failType & " refused the change - see the report." & vbCrLf & vbCrLf, "") & _
           IIf(noWork > 0, noWork & " slot(s) still have no Work in hours and will be skipped." & vbCrLf & vbCrLf, "") & _
           "Next: RS_Validate, then RS_AutoStaff.", vbInformation, "Role Staffing"
End Sub

' Manual scheduling arrived in Project 2010. On anything older the property
' isn't there and every task is auto scheduled by definition.
Private Function IsManual(t As Task) As Boolean
    On Error Resume Next
    IsManual = CBool(t.Manual)
End Function

Private Function PredsCount(t As Task) As Long
    Dim x As Task, n As Long
    On Error Resume Next
    For Each x In t.PredecessorTasks
        If Not x Is Nothing Then n = n + 1
    Next x
    PredsCount = n
End Function
