Attribute VB_Name = "RS_ModelProbe"
Option Explicit
'=============================================================================
' Asks THIS copy of MS Project which object-model members it actually has,
' and writes the answers to a text file to bring back.
'
' WHY: the type model we check our VBA against was assembled from Microsoft's
' published reference. Published references drift from shipped type libraries,
' and a model that claims a member exists when it doesn't is worse than no
' model - it blesses a typo. This closes that gap with evidence.
'
' TO RUN:
'   1. Alt+F11 in MS Project
'   2. Insert > Module, paste all of this in
'   3. click inside ExportProjectModel and press F5
'   4. a MsgBox gives you the file path - send that file back
'
' Open a real project file first (one with tasks, resources and assignments),
' or the members that need a sample object can't be asked. Use a COPY.
'
' WHAT THIS READS, AND WHY THAT DISTINCTION MATTERS
'
' Version 1 of this macro claimed to be read-only because it only ever used
' CallByName with VbGet. That was wrong, and it closed MS Project.
'
'   CallByName(obj, name, VbGet) on a zero-argument METHOD does not read
'   anything. It CALLS it.
'
' Probing Application in alphabetical order therefore ran CalculateAll,
' CalculateProject, CloseUndoTransaction, LevelNow - which re-levels the whole
' project and can move dates - and then Quit, which is why Project vanished.
' It stopped there only because Application sorts before Task; another few
' names and it would have called Task.Delete the same way.
'
' So this version:
'   - probes PROPERTIES only. Methods are listed as NOT-PROBED-METHOD and
'     never touched, because there is no way to test whether a method exists
'     without running it.
'   - skips Application entirely. Its members ARE the command surface, and
'     nothing about it is type-checked anyway.
'   - refuses a hard-coded list of names whatever the model says about them,
'     in case a method is ever mislabelled as a property.
'
' Reads are still late-bound, so a member your version lacks is a runtime
' error this records rather than a compile error that stops the module.
'
' GENERATED by tools/make_probe_macro.py - edit the model, not this.
'=============================================================================

Private mOut As String

Public Sub ExportProjectModel()
    Dim app As Object, path As String, n As Long
    Set app = Application

    ' Asking first, because the previous version of this macro closed
    ' Project without warning.
    If MsgBox("Read the object model of this project and write a report?" & _
              vbCrLf & vbCrLf & "Project: " & ProjName(app) & vbCrLf & vbCrLf & _
              "Properties are read; methods are NOT called. Nothing is " & _
              "written to your project." & vbCrLf & vbCrLf & _
              "Even so, use a copy of the file if it matters.", _
              vbOKCancel + vbQuestion, "RS Model Probe") <> vbOK Then Exit Sub

    mOut = ""
    Say "RS PROJECT MODEL PROBE v3 - properties only, Set retry"
    Say "generated-from: models/msproject.json"
    Say ""

    Header app
    Refs app
    Fields app
    n = Members(app)

    Say ""
    Say "END - " & n & " members probed"

    path = OutPath(app)
    If WriteOut(path) Then
        MsgBox "Written to:" & vbCrLf & vbCrLf & path & vbCrLf & vbCrLf & _
               "Send that file back. " & n & " members were probed.", _
               vbInformation, "RS Model Probe"
    Else
        MsgBox "Couldn't write the file. The report is in the Immediate " & _
               "window instead (Ctrl+G) - copy from there.", _
               vbExclamation, "RS Model Probe"
        Debug.Print mOut
    End If
End Sub

Private Function ProjName(ByVal app As Object) As String
    On Error Resume Next
    ProjName = app.ActiveProject.Name
    If Len(ProjName) = 0 Then ProjName = "(none open)"
    Err.Clear
End Function

'--- what version are we even talking to ------------------------------------
Private Sub Header(ByVal app As Object)
    Say "[HOST]"
    SayTry app, "Name"
    SayTry app, "Version"
    SayTry app, "Build"
    SayTry app, "OperatingSystem"
    SayTry app, "Path"
    On Error Resume Next
    Say "ActiveProject.Name=" & app.ActiveProject.Name
    Say "Tasks.Count=" & app.ActiveProject.Tasks.Count
    Say "Resources.Count=" & app.ActiveProject.Resources.Count
    Err.Clear
    On Error GoTo 0
    Say ""
End Sub

' One member, reported whatever happens. Late-bound, so a member this version
' hasn't got is an error string rather than a module that won't compile.
Private Sub SayTry(ByVal o As Object, ByVal nm As String)
    On Error Resume Next
    Dim v As Variant
    v = CallByName(o, nm, VbGet)
    If Err.Number = 0 Then
        Say nm & "=" & CStr(v)
    Else
        Say nm & "=<err " & Err.Number & ">"
    End If
    Err.Clear
    On Error GoTo 0
End Sub

'--- which type libraries this project references ---------------------------
' The exact GUID and version is what tells us which MSPRJ typelib the model
' should be matched against. Needs "Trust access to the VBA project object
' model" in Trust Center > Macro Settings; says so plainly when it's blocked.
Private Sub Refs(ByVal app As Object)
    Dim vbp As Object, r As Object, n As Long
    Say "[REFERENCES]"
    On Error Resume Next
    Set vbp = app.VBE.ActiveVBProject
    If vbp Is Nothing Or Err.Number <> 0 Then
        Say "BLOCKED - no VBE access (Trust Center > Macro Settings >"
        Say "          Trust access to the VBA project object model)"
        Err.Clear
        Say ""
        Exit Sub
    End If
    For Each r In vbp.References
        n = n + 1
        Say "ref" & n & "|name=" & r.Name & "|guid=" & r.GUID & _
            "|ver=" & r.Major & "." & r.Minor & "|builtin=" & r.BuiltIn
        Say "      desc=" & r.Description
        Say "      path=" & r.FullPath
    Next r
    Err.Clear
    On Error GoTo 0
    Say ""
End Sub

'--- field names and the constants behind them ------------------------------
' Our code finds columns by their LABEL, so the mapping between a label, its
' Text number and its pj constant is the part we most need to be right about.
' pjStandard didn't exist and cost a module; this is where that gets caught.
Private Sub Fields(ByVal app As Object)
    Dim i As Long, k As Long, nm As String, c As Variant, loc As Variant
    Say "[FIELDS]"
    Say "# name | FieldNameToFieldConstant(name, kind) per kind 0,1,2 |"
    Say "#        CustomFieldGetName(constant) = the label in THIS file"
    On Error Resume Next
    For k = 0 To 2
        For i = 1 To 30
            nm = "Text" & i
            Err.Clear
            c = app.FieldNameToFieldConstant(nm, k)
            If Err.Number = 0 Then
                Err.Clear
                loc = app.CustomFieldGetName(c)
                If Err.Number <> 0 Then loc = ""
                Say "kind" & k & "|" & nm & "|const=" & c & "|label=" & loc
            Else
                Say "kind" & k & "|" & nm & "|const=<err " & Err.Number & ">"
            End If
        Next i
    Next k
    Err.Clear
    On Error GoTo 0
    Say ""
End Sub

'--- the actual point: does each member in our model exist here? ------------
Private Function Members(ByVal app As Object) As Long
    Dim o As Object, names As Variant, i As Long, n As Long
    Say "[MEMBERS]"
    Say "# class|member|OK        member exists and reads"
    Say "#              ARGS      exists but needs arguments (still exists)"
    Say "#              MISSING   438 - not a member of this version"
    Say "#              ERR<n>    exists, read failed for another reason"

    ' ---- Assignment (261 members)
    Set o = Nothing
    On Error Resume Next
    Set o = FirstAsg(app)
    Err.Clear
    On Error GoTo 0
    If o Is Nothing Then
        Say "Assignment|<no sample object - open a project with tasks, resources and assignments>"
    Else
        names = Split("AppendNotes|Delete|EnterpriseTeamMember|Replan|TimeScaleData", "|")
        For i = LBound(names) To UBound(names)
            Say "Assignment|" & names(i) & "|NOT-PROBED-METHOD"
        Next i
        names = Split("ACWP|ActualCost|ActualFinish|ActualOvertimeCost|ActualOvertimeWork|ActualStart|ActualWork|Application|BCWP|BCWS|Baseline10BudgetCost|Baseline10BudgetWork|Baseline10Cost|Baseline10Finish|Baseline10Start|Baseline10Work|Baseline1BudgetCost|Baseline1BudgetWork|Baseline1Cost|Baseline1Finish|Baseline1Start|Baseline1Work|Baseline2BudgetCost|Baseline2BudgetWork|Baseline2Cost|Baseline2Finish|Baseline2Start|Baseline2Work|Baseline3BudgetCost|Baseline3BudgetWork|Baseline3Cost|Baseline3Finish|Baseline3Start|Baseline3Work|Baseline4BudgetCost|Baseline4BudgetWork|Baseline4Cost|Baseline4Finish|Baseline4Start|Baseline4Work|Baseline5BudgetCost|Baseline5BudgetWork|Baseline5Cost|Baseline5Finish|Baseline5Start|Baseline5Work|Baseline6BudgetCost|Baseline6BudgetWork|Baseline6Cost|Baseline6Finish|Baseline6Start", "|")
        For i = LBound(names) To UBound(names)
            Probe "Assignment", o, CStr(names(i))
            n = n + 1
        Next i
        names = Split("Baseline6Work|Baseline7BudgetCost|Baseline7BudgetWork|Baseline7Cost|Baseline7Finish|Baseline7Start|Baseline7Work|Baseline8BudgetCost|Baseline8BudgetWork|Baseline8Cost|Baseline8Finish|Baseline8Start|Baseline8Work|Baseline9BudgetCost|Baseline9BudgetWork|Baseline9Cost|Baseline9Finish|Baseline9Start|Baseline9Work|BaselineBudgetCost|BaselineBudgetWork|BaselineCost|BaselineFinish|BaselineStart|BaselineWork|BookingType|BudgetCost|BudgetWork|CV|Compliant|Confirmed|Cost|Cost1|Cost10|Cost2|Cost3|Cost4|Cost5|Cost6|Cost7|Cost8|Cost9|CostRateTable|CostVariance|Created|Date1|Date10|Date2|Date3|Date4|Date5|Date6|Date7|Date8|Date9|Delay|Duration1|Duration10|Duration2|Duration3|Duration4|Duration5|Duration6|Duration7|Duration8|Duration9|Finish|Finish1|Finish10|Finish2|Finish3|Finish4|Finish5|Finish6", "|")
        For i = LBound(names) To UBound(names)
            Probe "Assignment", o, CStr(names(i))
            n = n + 1
        Next i
        names = Split("Finish7|Finish8|Finish9|FinishVariance|FixedMaterialAssignment|Flag1|Flag10|Flag11|Flag12|Flag13|Flag14|Flag15|Flag16|Flag17|Flag18|Flag19|Flag2|Flag20|Flag3|Flag4|Flag5|Flag6|Flag7|Flag8|Flag9|Guid|Hyperlink|HyperlinkAddress|HyperlinkHREF|HyperlinkScreenTip|HyperlinkSubAddress|Index|LevelingDelay|LinkedFields|Notes|Number1|Number10|Number11|Number12|Number13|Number14|Number15|Number16|Number17|Number18|Number19|Number2|Number20|Number3|Number4|Number5|Number6|Number7|Number8|Number9|Overallocated|OvertimeCost|OvertimeWork|Owner|Parent|Peak|PercentWorkComplete|Project|RegularWork|RemainingCost|RemainingOvertimeCost|RemainingOvertimeWork|RemainingWork|Resource|ResourceGuid|ResourceID|ResourceName|ResourceRequestType|ResourceType|ResourceUniqueID|ResponsePending|SV|Start|Start1|Start10", "|")
        For i = LBound(names) To UBound(names)
            Probe "Assignment", o, CStr(names(i))
            n = n + 1
        Next i
        names = Split("Start2|Start3|Start4|Start5|Start6|Start7|Start8|Start9|StartVariance|Summary|Task|TaskGuid|TaskID|TaskName|TaskOutlineNumber|TaskSummaryName|TaskUniqueID|TeamStatusPending|Text1|Text10|Text11|Text12|Text13|Text14|Text15|Text16|Text17|Text18|Text19|Text2|Text20|Text21|Text22|Text23|Text24|Text25|Text26|Text27|Text28|Text29|Text3|Text30|Text4|Text5|Text6|Text7|Text8|Text9|UniqueID|Units|UpdateNeeded|VAC|WBS|Work|WorkContour|WorkVariance", "|")
        For i = LBound(names) To UBound(names)
            Probe "Assignment", o, CStr(names(i))
            n = n + 1
        Next i
    End If

    ' ---- Assignments (3 members)
    Set o = Nothing
    On Error Resume Next
    Set o = FirstTask(app).Assignments
    Err.Clear
    On Error GoTo 0
    If o Is Nothing Then
        Say "Assignments|<no sample object - open a project with tasks, resources and assignments>"
    Else
        names = Split("Add|Item|UniqueID", "|")
        For i = LBound(names) To UBound(names)
            Say "Assignments|" & names(i) & "|NOT-PROBED-METHOD"
        Next i
        names = Split("Application|Count|Parent", "|")
        For i = LBound(names) To UBound(names)
            Probe "Assignments", o, CStr(names(i))
            n = n + 1
        Next i
    End If

    ' ---- Project (176 members)
    Set o = Nothing
    On Error Resume Next
    Set o = app.ActiveProject
    Err.Clear
    On Error GoTo 0
    If o Is Nothing Then
        Say "Project|<no sample object - open a project with tasks, resources and assignments>"
    Else
        names = Split("Activate|AppendNotes|BaselineSavedDate|CheckIn|CheckoutProject|DeliverableAcceptChanges|DeliverableCreate|DeliverableDelete|DeliverableDependencyCreate|DeliverableDependencyDelete|DeliverableLinkToProject|DeliverableLinkToTask|DeliverableRefreshServerCache|DeliverableUpdate|DeliverablesClearAll|DeliverablesGetByProject|DeliverablesGetProviderProjects|DeliverablesGetServerCachedXml|DeliverablesGetXml|ExportAsFixedFormat|GetDisplayNameFromObjectMatchingID|GetObjectMatchingID|GetServerProjectGuid|GetTaskIndexByGuid|GetWinprojURLs|HideCheckoutMsgBar|ImportResourceErrorCount|LevelClearDates|LocalResourceCount|LocalResourceErrorCount|MakeServerURLTrusted|ReadWssData|ResourceCount|ResourceErrorCount|SaveAs|SetCustomUI|SetObjectMatchingID", "|")
        For i = LBound(names) To UBound(names)
            Say "Project|" & names(i) & "|NOT-PROBED-METHOD"
        Next i
        names = Split("AcceptNewExternalData|AdministrativeProject|AllowTaskDelegation|AndMoveCompleted|AndMoveRemaining|Application|AskForCompletedWork|AutoAddResources|AutoCalcCosts|AutoFilter|AutoLinkTasks|AutoSplitTasks|AutoTrack|BaseCalendars|BuiltinDocumentProperties|Calendar|CanCheckIn|CodeName|CommandBars|Container|CreationDate|CurrencyCode|CurrencyDigits|CurrencySymbol|CurrencySymbolPosition|CurrentDate|CurrentFilter|CurrentGroup|CurrentTable|CurrentView|CustomDocumentProperties|DatabaseProjectUniqueID|DayLabelDisplay|DaysPerMonth|DefaultDurationUnits|DefaultEarnedValueMethod|DefaultEffortDriven|DefaultFinishTime|DefaultFixedCostAccrual|DefaultResourceOvertimeRate|DefaultResourceStandardRate|DefaultStartTime|DefaultTaskType|DefaultWorkUnits|DetectCycle|DisplayProjectSummaryTask|DocumentLibraryVersions", "|")
        For i = LBound(names) To UBound(names)
            Probe "Project", o, CStr(names(i))
            n = n + 1
        Next i
        names = Split("EarnedValueBaseline|Engagements|EnterpriseActualsSynched|ExpandDatabaseTimephasedData|FollowedHyperlinkColor|FollowedHyperlinkColorEx|FullName|HasPassword|HonorConstraints|HourLabelDisplay|HoursPerDay|HoursPerWeek|HyperlinkColor|HyperlinkColorEx|ID|Index|IsCheckoutMsgBarVisible|IsCheckoutOSVisible|IsTemplate|KeepTaskOnNearestWorkingTimeWhenMadeAutoScheduled|LastPrintedDate|LastSaveDate|LastSavedBy|LastWssSyncDate|LevelEntireProject|LevelFromDate|LevelToDate|ManuallyScheduledTasksAutoRespectLinks|MapList|MinuteLabelDisplay|MonthLabelDisplay|MoveCompleted|MoveRemaining|MultipleCriticalPaths|Name|NewTasksAreManual|NewTasksCreatedAsManual|NewTasksEstimated|NumberOfResources|NumberOfTasks|OutlineChildren|OutlineCodes|Parent|Path|PhoneticType|ProjectFinish|ProjectGuideContent", "|")
        For i = LBound(names) To UBound(names)
            Probe "Project", o, CStr(names(i))
            n = n + 1
        Next i
        names = Split("ProjectGuideFunctionalLayoutPage|ProjectGuideSaveBuffer|ProjectGuideUseDefaultContent|ProjectGuideUseDefaultFunctionalLayoutPage|ProjectNamePrefix|ProjectNotes|ProjectServerUsedForTracking|ProjectStart|ProjectSummaryTask|ReadOnly|ReadOnlyRecommended|ReceiveNotifications|RemoveFileProperties|ReportList|Reports|ResourceFilterList|ResourceFilters|ResourceGroupList|ResourceGroups|ResourceGroups2|ResourcePoolName|ResourceTableList|ResourceTables|ResourceViewList|Resources|RevisionNumber|Saved|ScheduleFromStart|SendHyperlinkNote|ServerIdentification|ServerURL|SharedWorkspace|ShowCriticalSlack|ShowCrossProjectLinksInfo|ShowEstimatedDuration|ShowExternalPredecessors|ShowExternalSuccessors|ShowTaskSuggestions|ShowTaskWarnings|SpaceBeforeTimeLabels|SpreadCostsToStatusDate", "|")
        For i = LBound(names) To UBound(names)
            Probe "Project", o, CStr(names(i))
            n = n + 1
        Next i
        names = Split("SpreadPercentCompleteToStatusDate|StartOnCurrentDate|StartWeekOn|StartYearIn|StatusDate|Subprojects|TaskErrorCount|TaskFilterList|TaskFilters|TaskGroupList|TaskGroups|TaskGroups2|TaskTableList|TaskTables|TaskViewList|Tasks|Template|Timeline|TrackingMethod|Type|UnderlineHyperlinks|UniqueID|UpdateProjOnSave|UseFYStartYear|UserControl|UtilizationDate|UtilizationType|VBASigned|VBProject|VersionName|ViewList|Views|ViewsCombination|ViewsSingle|WBSCodeGenerate|WBSVerifyUniqueness|WeekLabelDisplay|Windows|Windows2|WriteReserved|YearLabelDisplay", "|")
        For i = LBound(names) To UBound(names)
            Probe "Project", o, CStr(names(i))
            n = n + 1
        Next i
    End If

    ' ---- Resource (276 members)
    Set o = Nothing
    On Error Resume Next
    Set o = FirstRes(app)
    Err.Clear
    On Error GoTo 0
    If o Is Nothing Then
        Say "Resource|<no sample object - open a project with tasks, resources and assignments>"
    Else
        names = Split("AppendNotes|Delete|EnterpriseTeamMember|GetField|Level|SetField|TimeScaleData", "|")
        For i = LBound(names) To UBound(names)
            Say "Resource|" & names(i) & "|NOT-PROBED-METHOD"
        Next i
        names = Split("ACWP|AccrueAt|ActualCost|ActualOvertimeCost|ActualOvertimeWork|ActualWork|Application|Assignments|Availabilities|AvailableFrom|AvailableTo|BCWP|BCWS|BaseCalendar|Baseline10BudgetCost|Baseline10BudgetWork|Baseline10Cost|Baseline10Work|Baseline1BudgetCost|Baseline1BudgetWork|Baseline1Cost|Baseline1Work|Baseline2BudgetCost|Baseline2BudgetWork|Baseline2Cost|Baseline2Work|Baseline3BudgetCost|Baseline3BudgetWork|Baseline3Cost|Baseline3Work|Baseline4BudgetCost|Baseline4BudgetWork|Baseline4Cost|Baseline4Work|Baseline5BudgetCost|Baseline5BudgetWork|Baseline5Cost|Baseline5Work|Baseline6BudgetCost|Baseline6BudgetWork|Baseline6Cost|Baseline6Work|Baseline7BudgetCost|Baseline7BudgetWork|Baseline7Cost|Baseline7Work|Baseline8BudgetCost|Baseline8BudgetWork|Baseline8Cost|Baseline8Work|Baseline9BudgetCost", "|")
        For i = LBound(names) To UBound(names)
            Probe "Resource", o, CStr(names(i))
            n = n + 1
        Next i
        names = Split("Baseline9BudgetWork|Baseline9Cost|Baseline9Work|BaselineBudgetCost|BaselineBudgetWork|BaselineCost|BaselineWork|BookingType|Budget|BudgetCost|BudgetWork|CV|Calendar|CalendarGuid|CanLevel|Code|Compliant|Confirmed|Cost|Cost1|Cost10|Cost2|Cost3|Cost4|Cost5|Cost6|Cost7|Cost8|Cost9|CostCenter|CostPerUse|CostRateTables|CostVariance|Created|Date1|Date10|Date2|Date3|Date4|Date5|Date6|Date7|Date8|Date9|DefaultAssignmentOwner|Duration1|Duration10|Duration2|Duration3|Duration4|Duration5|Duration6|Duration7|Duration8|Duration9|EMailAddress|EngagementCommittedFinish|EngagementCommittedMaxUnits|EngagementCommittedStart|EngagementCommittedWork|EngagementDraftFinish|EngagementDraftMaxUnits|EngagementDraftStart|EngagementDraftWork|EngagementProposedFinish|EngagementProposedMaxUnits|EngagementProposedStart", "|")
        For i = LBound(names) To UBound(names)
            Probe "Resource", o, CStr(names(i))
            n = n + 1
        Next i
        names = Split("EngagementProposedWork|Enterprise|EnterpriseBaseCalendar|EnterpriseCheckedOutBy|EnterpriseGeneric|EnterpriseInactive|EnterpriseIsCheckedOut|EnterpriseLastModifiedDate|EnterpriseNameUsed|EnterpriseRequiredValues|EnterpriseUniqueID|ErrorMessage|Finish1|Finish10|Finish2|Finish3|Finish4|Finish5|Finish6|Finish7|Finish8|Finish9|Flag1|Flag10|Flag11|Flag12|Flag13|Flag14|Flag15|Flag16|Flag17|Flag18|Flag19|Flag2|Flag20|Flag3|Flag4|Flag5|Flag6|Flag7|Flag8|Flag9|Group|GroupBySummary|Guid|Hyperlink|HyperlinkAddress|HyperlinkHREF|HyperlinkScreenTip|HyperlinkSubAddress|ID|Import|Index|Initials|IsLocked|IsTeam|LinkedFields|MaterialLabel|MaxUnits|Name|Notes|Number1|Number10|Number11|Number12|Number13|Number14|Number15|Number16|Number17|Number18|Number19|Number2|Number20|Number3|Number4|Number5|Number6", "|")
        For i = LBound(names) To UBound(names)
            Probe "Resource", o, CStr(names(i))
            n = n + 1
        Next i
        names = Split("Number7|Number8|Number9|Objects|OutlineCode1|OutlineCode10|OutlineCode2|OutlineCode3|OutlineCode4|OutlineCode5|OutlineCode6|OutlineCode7|OutlineCode8|OutlineCode9|Overallocated|OvertimeCost|OvertimeRate|OvertimeWork|Parent|PayRates|PeakUnits|PercentWorkComplete|Phonetics|Project|RegularWork|RemainingCost|RemainingOvertimeCost|RemainingOvertimeWork|RemainingWork|ResponsePending|SV|StandardRate|Start1|Start10|Start2|Start3|Start4|Start5|Start6|Start7|Start8|Start9|TeamStatusPending|Text1|Text10|Text11|Text12|Text13|Text14|Text15|Text16|Text17|Text18|Text19|Text2|Text20|Text21|Text22|Text23|Text24|Text25|Text26|Text27|Text28|Text29|Text3|Text30|Text4|Text5|Text6|Text7|Text8|Text9|Type|UniqueID|UpdateNeeded|VAC|WindowsUserAccount|Work|WorkVariance", "|")
        For i = LBound(names) To UBound(names)
            Probe "Resource", o, CStr(names(i))
            n = n + 1
        Next i
    End If

    ' ---- Resources (3 members)
    Set o = Nothing
    On Error Resume Next
    Set o = app.ActiveProject.Resources
    Err.Clear
    On Error GoTo 0
    If o Is Nothing Then
        Say "Resources|<no sample object - open a project with tasks, resources and assignments>"
    Else
        names = Split("Add|Item|UniqueID", "|")
        For i = LBound(names) To UBound(names)
            Say "Resources|" & names(i) & "|NOT-PROBED-METHOD"
        Next i
        names = Split("Application|Count|Parent", "|")
        For i = LBound(names) To UBound(names)
            Probe "Resources", o, CStr(names(i))
            n = n + 1
        Next i
    End If

    ' ---- Task (459 members)
    Set o = Nothing
    On Error Resume Next
    Set o = FirstTask(app)
    Err.Clear
    On Error GoTo 0
    If o Is Nothing Then
        Say "Task|<no sample object - open a project with tasks, resources and assignments>"
    Else
        names = Split("AppendNotes|Delete|GetField|LinkPredecessors|LinkSuccessors|OutlineHideSubTasks|OutlineIndent|OutlineOutdent|OutlineShowAllTasks|OutlineShowSubTasks|Resume|SetField|Split|Stop|TimeScaleData|UnlinkPredecessors|UnlinkSuccessors", "|")
        For i = LBound(names) To UBound(names)
            Say "Task|" & names(i) & "|NOT-PROBED-METHOD"
        Next i
        names = Split("ACWP|Active|ActualCost|ActualDuration|ActualFinish|ActualOvertimeCost|ActualOvertimeWork|ActualStart|ActualWork|Application|Assignments|BCWP|BCWS|Baseline10BudgetCost|Baseline10BudgetWork|Baseline10Cost|Baseline10DeliverableFinish|Baseline10DeliverableStart|Baseline10Duration|Baseline10DurationEstimated|Baseline10DurationText|Baseline10Finish|Baseline10FinishText|Baseline10FixedCost|Baseline10FixedCostAccrual|Baseline10Start|Baseline10StartText|Baseline10Work|Baseline1BudgetCost|Baseline1BudgetWork|Baseline1Cost|Baseline1DeliverableFinish|Baseline1DeliverableStart|Baseline1Duration|Baseline1DurationEstimated|Baseline1DurationText|Baseline1Finish|Baseline1FinishText|Baseline1FixedCost|Baseline1FixedCostAccrual|Baseline1Start|Baseline1StartText|Baseline1Work|Baseline2BudgetCost", "|")
        For i = LBound(names) To UBound(names)
            Probe "Task", o, CStr(names(i))
            n = n + 1
        Next i
        names = Split("Baseline2BudgetWork|Baseline2Cost|Baseline2DeliverableFinish|Baseline2DeliverableStart|Baseline2Duration|Baseline2DurationEstimated|Baseline2DurationText|Baseline2Finish|Baseline2FinishText|Baseline2FixedCost|Baseline2FixedCostAccrual|Baseline2Start|Baseline2StartText|Baseline2Work|Baseline3BudgetCost|Baseline3BudgetWork|Baseline3Cost|Baseline3DeliverableFinish|Baseline3DeliverableStart|Baseline3Duration|Baseline3DurationEstimated|Baseline3DurationText|Baseline3Finish|Baseline3FinishText|Baseline3FixedCost|Baseline3FixedCostAccrual|Baseline3Start|Baseline3StartText|Baseline3Work|Baseline4BudgetCost|Baseline4BudgetWork|Baseline4Cost|Baseline4DeliverableFinish|Baseline4DeliverableStart|Baseline4Duration|Baseline4DurationEstimated|Baseline4DurationText|Baseline4Finish|Baseline4FinishText", "|")
        For i = LBound(names) To UBound(names)
            Probe "Task", o, CStr(names(i))
            n = n + 1
        Next i
        names = Split("Baseline4FixedCost|Baseline4FixedCostAccrual|Baseline4Start|Baseline4StartText|Baseline4Work|Baseline5BudgetCost|Baseline5BudgetWork|Baseline5Cost|Baseline5DeliverableFinish|Baseline5DeliverableStart|Baseline5Duration|Baseline5DurationEstimated|Baseline5DurationText|Baseline5Finish|Baseline5FinishText|Baseline5FixedCost|Baseline5FixedCostAccrual|Baseline5Start|Baseline5StartText|Baseline5Work|Baseline6BudgetCost|Baseline6BudgetWork|Baseline6Cost|Baseline6DeliverableFinish|Baseline6DeliverableStart|Baseline6Duration|Baseline6DurationEstimated|Baseline6DurationText|Baseline6Finish|Baseline6FinishText|Baseline6FixedCost|Baseline6FixedCostAccrual|Baseline6Start|Baseline6StartText|Baseline6Work|Baseline7BudgetCost|Baseline7BudgetWork|Baseline7Cost|Baseline7DeliverableFinish", "|")
        For i = LBound(names) To UBound(names)
            Probe "Task", o, CStr(names(i))
            n = n + 1
        Next i
        names = Split("Baseline7DeliverableStart|Baseline7Duration|Baseline7DurationEstimated|Baseline7DurationText|Baseline7Finish|Baseline7FinishText|Baseline7FixedCost|Baseline7FixedCostAccrual|Baseline7Start|Baseline7StartText|Baseline7Work|Baseline8BudgetCost|Baseline8BudgetWork|Baseline8Cost|Baseline8DeliverableFinish|Baseline8DeliverableStart|Baseline8Duration|Baseline8DurationEstimated|Baseline8DurationText|Baseline8Finish|Baseline8FinishText|Baseline8FixedCost|Baseline8FixedCostAccrual|Baseline8Start|Baseline8StartText|Baseline8Work|Baseline9BudgetCost|Baseline9BudgetWork|Baseline9Cost|Baseline9DeliverableFinish|Baseline9DeliverableStart|Baseline9Duration|Baseline9DurationEstimated|Baseline9DurationText|Baseline9Finish|Baseline9FinishText|Baseline9FixedCost|Baseline9FixedCostAccrual|Baseline9Start", "|")
        For i = LBound(names) To UBound(names)
            Probe "Task", o, CStr(names(i))
            n = n + 1
        Next i
        names = Split("Baseline9StartText|Baseline9Work|BaselineBudgetCost|BaselineBudgetWork|BaselineCost|BaselineDeliverableFinish|BaselineDeliverableStart|BaselineDuration|BaselineDurationEstimated|BaselineDurationText|BaselineFinish|BaselineFinishText|BaselineFixedCost|BaselineFixedCostAccrual|BaselineStart|BaselineStartText|BaselineWork|BudgetCost|BudgetWork|CPI|CV|CVPercent|Calendar|CalendarGuid|CalendarObject|Compliant|Confirmed|ConstraintDate|ConstraintType|Contact|Cost|Cost1|Cost10|Cost2|Cost3|Cost4|Cost5|Cost6|Cost7|Cost8|Cost9|CostVariance|Created|Critical|Date1|Date10|Date2|Date3|Date4|Date5|Date6|Date7|Date8|Date9|Deadline|DeliverableFinish|DeliverableGuid|DeliverableName|DeliverableStart|DeliverableType|Duration|Duration1|Duration10|Duration10Estimated|Duration1Estimated|Duration2", "|")
        For i = LBound(names) To UBound(names)
            Probe "Task", o, CStr(names(i))
            n = n + 1
        Next i
        names = Split("Duration2Estimated|Duration3|Duration3Estimated|Duration4|Duration4Estimated|Duration5|Duration5Estimated|Duration6|Duration6Estimated|Duration7|Duration7Estimated|Duration8|Duration8Estimated|Duration9|Duration9Estimated|DurationText|DurationVariance|EAC|EarlyFinish|EarlyStart|EarnedValueMethod|EffortDriven|ErrorMessage|Estimated|ExternalTask|Finish|Finish1|Finish10|Finish2|Finish3|Finish4|Finish5|Finish6|Finish7|Finish8|Finish9|FinishSlack|FinishText|FinishVariance|FixedCost|FixedCostAccrual|Flag1|Flag10|Flag11|Flag12|Flag13|Flag14|Flag15|Flag16|Flag17|Flag18|Flag19|Flag2|Flag20|Flag3|Flag4|Flag5|Flag6|Flag7|Flag8|Flag9|FreeSlack|GroupBySummary|Guid|HideBar|Hyperlink|HyperlinkAddress|HyperlinkHREF|HyperlinkScreenTip|HyperlinkSubAddress|ID|IgnoreResourceCalendar|IgnoreWarnings|Index", "|")
        For i = LBound(names) To UBound(names)
            Probe "Task", o, CStr(names(i))
            n = n + 1
        Next i
        names = Split("IsDurationValid|IsFinishValid|IsPublished|IsStartValid|LateFinish|LateStart|LevelIndividualAssignments|LevelingCanSplit|LevelingDelay|LinkedFields|Manual|Marked|Milestone|Name|Notes|Number1|Number10|Number11|Number12|Number13|Number14|Number15|Number16|Number17|Number18|Number19|Number2|Number20|Number3|Number4|Number5|Number6|Number7|Number8|Number9|Objects|OutlineChildren|OutlineCode1|OutlineCode10|OutlineCode2|OutlineCode3|OutlineCode4|OutlineCode5|OutlineCode6|OutlineCode7|OutlineCode8|OutlineCode9|OutlineLevel|OutlineNumber|OutlineParent|Overallocated|OvertimeCost|OvertimeWork|Parent|PathDrivenSuccessor|PathDrivingPredecessor|PathPredecessor|PathSuccessor|PercentComplete|PercentWorkComplete|PhysicalPercentComplete|Placeholder|PredecessorTasks|Predecessors|PreleveledFinish", "|")
        For i = LBound(names) To UBound(names)
            Probe "Task", o, CStr(names(i))
            n = n + 1
        Next i
        names = Split("PreleveledStart|Priority|Project|RecalcFlags|Recurring|RegularWork|RemainingCost|RemainingDuration|RemainingOvertimeCost|RemainingOvertimeWork|RemainingWork|ResourceGroup|ResourceInitials|ResourceNames|ResourcePhonetics|Resources|ResponsePending|Rollup|SPI|SV|SVPercent|ScheduledDuration|ScheduledFinish|ScheduledStart|SplitParts|Start|Start1|Start10|Start2|Start3|Start4|Start5|Start6|Start7|Start8|Start9|StartDriver|StartSlack|StartText|StartVariance|Status|StatusManagerName|SubProjectReadOnly|Subproject|SuccessorTasks|Successors|Summary|TCPI|TaskDependencies|TeamStatusPending|Text1|Text10|Text11|Text12|Text13|Text14|Text15|Text16|Text17|Text18|Text19|Text2|Text20|Text21|Text22|Text23|Text24|Text25|Text26|Text27|Text28|Text29|Text3|Text30|Text4|Text5|Text6|Text7|Text8|Text9|TotalSlack|Type", "|")
        For i = LBound(names) To UBound(names)
            Probe "Task", o, CStr(names(i))
            n = n + 1
        Next i
        names = Split("UniqueID|UniqueIDPredecessors|UniqueIDSuccessors|UpdateNeeded|VAC|WBS|WBSPredecessors|WBSSuccessors|Warning|Work|WorkVariance", "|")
        For i = LBound(names) To UBound(names)
            Probe "Task", o, CStr(names(i))
            n = n + 1
        Next i
    End If

    ' ---- Tasks (3 members)
    Set o = Nothing
    On Error Resume Next
    Set o = app.ActiveProject.Tasks
    Err.Clear
    On Error GoTo 0
    If o Is Nothing Then
        Say "Tasks|<no sample object - open a project with tasks, resources and assignments>"
    Else
        names = Split("Add|Item|UniqueID", "|")
        For i = LBound(names) To UBound(names)
            Say "Tasks|" & names(i) & "|NOT-PROBED-METHOD"
        Next i
        names = Split("Application|Count|Parent", "|")
        For i = LBound(names) To UBound(names)
            Probe "Tasks", o, CStr(names(i))
            n = n + 1
        Next i
    End If

    Members = n
End Function

' WHAT 438 DOES AND DOESN'T TELL US
'
' "Object doesn't support this property or method" comes back for THREE
' different situations, and only one of them means the member is absent:
'
'   1. it really isn't a member of this version
'   2. it returns an object with no default property, so assigning it to a
'      Variant fails even though the member is fine - retried with Set below
'   3. it is write-only, or hidden in the type library and undocumented.
'      Nothing can distinguish this from case 1 by reading.
'
' Case 3 is not hypothetical. Project.NewTasksAreManual reports 438 here,
' is absent from Microsoft's published property list, and is nonetheless
' REAL - our own code assigns to it from an early-bound Project variable,
' which would not compile at all if the member didn't exist.
'
' So the label is NOT-READABLE, never MISSING. Removing something from the
' model needs this plus the documentation agreeing, not this alone.
Private Sub Probe(ByVal cls As String, ByVal o As Object, ByVal nm As String)
    Dim v As Variant, o2 As Object, e As Long
    On Error Resume Next
    v = CallByName(o, nm, VbGet)
    e = Err.Number
    Err.Clear

    If e = 438 Then
        ' Could just be an object with no default property.
        Set o2 = CallByName(o, nm, VbGet)
        If Err.Number = 0 Then
            Err.Clear
            On Error GoTo 0
            Say cls & "|" & nm & "|OK-OBJECT"
            Exit Sub
        End If
        Err.Clear
    End If
    On Error GoTo 0

    Select Case e
        Case 0
            Say cls & "|" & nm & "|OK"
        Case 449, 450
            Say cls & "|" & nm & "|ARGS"
        Case 438
            Say cls & "|" & nm & "|NOT-READABLE"
        Case Else
            Say cls & "|" & nm & "|ERR" & e
    End Select
End Sub

'--- sample objects, by navigation, read-only -------------------------------
' Not Tasks(1): a blank row or a row deleted earlier leaves a Nothing in the
' collection, and Project raises on it rather than returning Nothing.
Private Function FirstTask(ByVal app As Object) As Object
    Dim t As Object
    On Error Resume Next
    For Each t In app.ActiveProject.Tasks
        If Not t Is Nothing Then
            Set FirstTask = t
            Exit Function
        End If
    Next t
    Err.Clear
End Function

Private Function FirstRes(ByVal app As Object) As Object
    Dim r As Object
    On Error Resume Next
    For Each r In app.ActiveProject.Resources
        If Not r Is Nothing Then
            Set FirstRes = r
            Exit Function
        End If
    Next r
    Err.Clear
End Function

Private Function FirstAsg(ByVal app As Object) As Object
    Dim t As Object, a As Object
    On Error Resume Next
    For Each t In app.ActiveProject.Tasks
        If Not t Is Nothing Then
            For Each a In t.Assignments
                Set FirstAsg = a
                Exit Function
            Next a
        End If
    Next t
    Err.Clear
End Function

'--- output ----------------------------------------------------------------
Private Sub Say(ByVal s As String)
    mOut = mOut & s & vbCrLf
End Sub

' Next to the project file when there is one, TEMP otherwise. Never the Office
' install folder - that's read-only on a managed machine.
Private Function OutPath(ByVal app As Object) As String
    Dim folder As String
    On Error Resume Next
    folder = app.ActiveProject.Path
    Err.Clear
    If Len(folder) = 0 Then folder = Environ$("TEMP")
    If Len(folder) = 0 Then folder = Environ$("USERPROFILE")
    On Error GoTo 0
    OutPath = folder & "\RS_ProjectModel.txt"
End Function

Private Function WriteOut(ByVal path As String) As Boolean
    Dim f As Integer
    On Error GoTo Nope
    f = FreeFile
    Open path For Output As #f
    Print #f, mOut
    Close #f
    WriteOut = True
    Exit Function
Nope:
    On Error Resume Next
    Close #f
    WriteOut = False
End Function
